### DISCUSSION TITLE
Can I have dynamic types in arrays, e.g. `dsl.ArrayOf(dsl.AnyOf(TypeA, TypeB))`?

### DISCUSSION THREAD

**Discussion by gabyx** [goadesign/goa#3672] [Q&A]
I have an array which I want to represent in Goa DSL:

```yaml
- id: 1
  type: banana
  monkey: true
  
- id: 3
  type: orange 
  ripe: true
```

Can I represent such a type in Goa with the DSL? I did not find anything related to this?
Does that even exist?

Not even sure its even possible to represent that in Go easily...

Thanks a lot
