### ISSUE TITLE
Generate swagger consumes/produces for every action

### ISSUE THREAD

**Issue by ZandorZ** [goadesign/goa#1074]
I have an action that returns mimetype "application/vnd.myapp.user+json; type=collection" 
defined it in dsl by a collectionof MediaType("application/vnd.myapp.user+json")

Is there a way to define Consumes/Produces in every Action , not only on API ?
I tried it but it says: Invalid use of Produces in resource "user" action "list"

i need a generate swagger file that has defined the respective mimetype it actually produces
something like this:

```yaml
/users:
    get:
      description:
        Returns a list users
      consumes:
        - application/vnd.myapp.user+json
      produces:
        - application/vnd.myapp.user+json; type=collection
....
```
