### ISSUE TITLE
Support Security specs

### ISSUE THREAD

**Issue by abourget** [goadesign/goa#147]
In a swagger file, you can specify:

```
securityDefinitions:
  jwtAuth:
    type: apiKey
    name: Authorization
    in: header
security:
  - jwtAuth: []
```

and the Sagger edito and other things will help you authenticate. It also specifies to the user which authentication mechanism you want to use.

Also, it seems possible to list the security per action or resources..

It seems that would be a great addition to the DSL, having some sort of `SecurityDefinition(func() {}` and `Security("method")` somewhere, wouldn't it ?

Refs: http://swagger.io/specification/#securityDefinitionsObject
