### ISSUE TITLE
How to set readOnly attributes?

### ISSUE THREAD

**Issue by dikhan** [goadesign/goa#1736]
Hi guys,

Quick question: 

Is there any way to set an attribute as readOnly? Looks like the JsonSchema struct supports that but doesn't seem to be exposed in the DSL:

https://github.com/goadesign/goa/blob/0e29005325687f8fa60ecae75b156933ec81ba4f/goagen/gen_schema/json_schema.go#L32

Basically, I would like to produce a swagger that has the following definition:
````
definitions:
  MyDefinition:
    type: "object"
    required:
      - some_attribute
    properties:
      some_attribute:
        type: "string"
        readOnly: true # <-- How to set this?
````

Any help would be much appreciated.

Thanks,
Dani
