### ISSUE TITLE
V2: ResultType OpenAPI Doc Inconsistent

### ISSUE THREAD

**Issue by sachnk** [goadesign/goa#1907]
### Expected Behavior

When using a ResultType with a specific view on a method, the generated OpenAPI response definition should reflect the selected view.

### Actual Behavior

The generated OpenAPI response definition always uses the "default" view, and associated fields.

### Steps to Reproduce the Problem

Generate the following design on the latest V2 branch. The resulting OpenAPI response objects do not discriminate between the "default" and "tiny" views on the StoredUser ResultType. See sample OpenAPI definitions below as well.

```golang
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

var _ = Service("users", func() {
	Description("Manages auth users")
	HTTP(func() {
		Path("/auth/users")
	})

	Method("fetch", func() {
		Description("Fetch an existing user")
		Payload(func() {
			Attribute("user_id", Int64)
		})
		Result(StoredUser, func() {
			View("default")
		})
		HTTP(func() {
			GET("/{user_id}")
			Response(StatusOK)
		})
	})

	Method("create", func() {
		Description("Create a new user")
		Payload(func() {
			Attribute("email", String)
			Attribute("password", String)
			Required("email", "password")
		})
		Result(StoredUser, func() {
			View("tiny")
		})
		HTTP(func() {
			POST("")
			Response(StatusOK)
		})
	})
})

var StoredUser = ResultType("application/vnd.stored-user+json", func() {
	Description("A user")
	Attributes(func() {
		Attribute("id", UInt64)
		Attribute("email", String)
		Attribute("email_confirmed_at", String)
		Attribute("password_updated_at", String)
	})
	View("default", func() {
		Attribute("id")
		Attribute("email")
		Attribute("email_confirmed_at")
		Attribute("password_updated_at")
		Required("id", "email", "email_confirmed_at", "password_updated_at")
	})
	View("tiny", func() {
		Attribute("id")
		Attribute("email")
		Required("id", "email")
	})
	Required("id", "email")
})
```

Resulting OpenAPI response objects:

```yaml
  UsersCreateResponseBody:
    title: 'Mediatype identifier: application/vnd.stored-user+json; view=default'
    type: object
    properties:
      email:
        type: string
        example: Sit sit doloremque dolorem ad.
      email_confirmed_at:
        type: string
        example: Est quibusdam eaque et nulla commodi architecto.
      id:
        type: integer
        example: 6249017213720796647
        format: int64
      password_updated_at:
        type: string
        example: Dolorem distinctio.
    description: CreateResponseBody result type (default view)
    example:
      email: Quam voluptatem quia sapiente est sed accusamus.
      email_confirmed_at: Iure autem rerum.
      id: 1697851821866806001
      password_updated_at: Commodi fugit et voluptas.
    required:
    - id
    - email
  UsersFetchResponseBody:
    title: 'Mediatype identifier: application/vnd.stored-user+json; view=default'
    type: object
    properties:
      email:
        type: string
        example: Molestias laudantium sequi hic perspiciatis nobis.
      email_confirmed_at:
        type: string
        example: Quibusdam dolor numquam ut odit.
      id:
        type: integer
        example: 1307757192938295463
        format: int64
      password_updated_at:
        type: string
        example: Esse voluptas et.
    description: FetchResponseBody result type (default view)
    example:
      email: Magnam placeat error sed qui.
      email_confirmed_at: Ad inventore at omnis.
      id: 1347379500592278005
      password_updated_at: Commodi voluptatem alias dolore est.
    required:
    - id
    - email
```

### Specifications

  - goa Version: V2 @ 702c321d0f86bcdce8c2f36a4bf4b2f21230dc19
  - Platform (Linux/Windows etc.): Mac
