### ISSUE TITLE
swagger:example meta doesn't work

### ISSUE THREAD

**Issue by chezgi** [goadesign/goa#2834]
i dont want to create examples in swagger. it is very loudy when using git.
but using this meta tag also doesn't work

```go
	Meta("swagger:example", "false")
```

**Comment by raphael** [comment]
Thank you for the report, could you provide a repro with a simple design?

**Comment by chezgi** [comment]
sample code:
```go
package design
import (
	. "goa.design/goa/v3/dsl"
)
var _ = API("test", func() {
	Title("test api")
	Version("1.0")
	Meta("swagger:example", "false")
	Server("test", func() {
		Host("localhost", func() {
			Description("default host")
			URI("http://localhost:8000/")
		})
	})
})
var _ = Service("test", func() {
	Meta("swagger:example", "false")
	Method("get", func() {
		Payload(func() {
			Attribute("Label", String)
			Required("Label")
		})
		Result(func() {
			Attribute("Test", String)
		})
		HTTP(func() {
			GET("/{Label}")
		})
	})
})
```

result:
```yaml
definitions:
  TestGetResponseBody:
    title: TestGetResponseBody
    type: object
    properties:
      Test:
        type: string
        example: Vitae magni repellat minus minus dolor repellat.
    example:
      Test: Nostrum et eum et labore veritatis similique.
```
NOTE: openapi3.yaml hase more examples!

**Comment by chezgi** [comment]
when using meta in payload and result some of examples remains:
```go
package design

import (
	. "goa.design/goa/v3/dsl"
)

var _ = API("test", func() {
	Title("test api")
	Version("1.0")
	Meta("swagger:example", "false")

	Server("test", func() {
		Host("localhost", func() {
			Description("default host")
			URI("http://localhost:8000/")
		})
	})

})

var _ = Service("test", func() {
	Meta("swagger:example", "false")

	Method("get", func() {
		Payload(func() {
			Meta("swagger:example", "false")
			Attribute("Label", String)
			Required("Label")
		})
		Result(func() {
			Meta("swagger:example", "false")
			Attribute("Test", String)
		})
		HTTP(func() {
			GET("/{Label}")
		})
	})
})
```
result:
```yaml
definitions:
  TestGetResponseBody:
    title: TestGetResponseBody
    type: object
    properties:
      Test:
        type: string
        example: Qui rem qui earum.
```
