### ISSUE TITLE
The files dsl with a wildcard; Files("/my/{*filepath}, ...), generates invalid openapi3.yaml

### ISSUE THREAD

**Issue by EmilLaursen** [goadesign/goa#2843]
I caught this with validation tools. In particular, `openapi-generator-cli` catches one error, and the `swagger-editor` catches both errors.
Using a `Files("/my/{*filepath}, ...)` expression to generate a fileserver in `design.go`, will give you `openapi3.yaml` of the form (example):
```yaml
  '/docs/swagger/{*filepath}':
    get:
      tags:
        - apidocs
      summary: Download ./pgQueue/swagger
      operationId: 'apidocs#/docs/swagger/{*filepath}'
      parameters:
        - name: filepath
          in: path
          description: Relative file path
          required: true
```
This violates two parts of the [OpenAPI 3 spec](https://swagger.io/specification/#parameter-object):
1) The parameter object does not contain a schema or content property
> A parameter MUST contain either a schema property, or a content property, but not both
2) The parameter name, must match the expression inside the URL. In this case it should be `"*filepath"` instead of `filepath`. here is a quote from the spec:
> If **in** is "path", the name field MUST correspond to a template expression occurring within the path field in the Paths Object.

Explicitly, if it looked like this, it would generate no errors:

```yaml
  '/docs/swagger/{*filepath}':
    get:
      tags:
        - apidocs
      summary: Download ./pgQueue/swagger
      operationId: 'apidocs#/docs/swagger/{*filepath}'
      parameters:
        - name: "*filepath"
          in: path
          description: Relative file path
          required: true
          schema:
            type: string
```

I do not have experience with the codebase, so this might be very wrong. But it would seem this might be a simple change to the parameter object [defined here](https://github.com/goadesign/goa/blob/314933771aaf6df29765e81165e57100ebb71363/http/codegen/openapi/v3/builder.go#L302)
