### ISSUE TITLE
Query parameter mapped via MapParams is not present in OpenAPI spec

### ISSUE THREAD

**Issue by nya1** [goadesign/goa#3053]
Using Goa version v3.7.2

[Design example to reproduce](https://github.com/nya1/goa-mapparams-repro/tree/master/design/design.go)

The expected `metadata` Attribute of `MapOf(String, String)` type is
mapped to the HTTP transport as  `MapParams("metadata")`

The `metadata` query parameter can be passed to the URL as the following:
`GET /multiply/?metadata[testKey]=val`

The service will correctly receive `map[testKey:val]`, but the [OpenAPI generated](https://github.com/nya1/goa-mapparams-repro/tree/master/gen/http/openapi3.yaml#L15)
it's not listing the `metadata` in the endpoint.

## Expected

`metadata` query parameter to be present in OpenAPI like the other mapped attributes, example:

```
      parameters:
      - in: query
        name: metadata
        description: this should be on openapi
        required: false
        schema:
          type: object
          additionalProperties: true
          example:
            testKey: val
        style: deepObject
```

You can find all files / setup to reproduce the issue: https://github.com/nya1/goa-mapparams-repro
