### ISSUE TITLE
Oneof not properly populating openapi3 yaml

### ISSUE THREAD

**Issue by JeffKahn1212** [goadesign/goa#3206]
When using the GOA DSL to define the schema for an appropriate structure response when querying the server API, I used the following Types utilizing the built-in OneOf function.

``` golang
var Topology = Type("Topology", func() {
	Description("Feeder Topology")
	Attribute("nodes", ArrayOf(node), "Nodes" , func() {
	})
})


var node = Type("Node", func() {
	OneOf("Attribute", func() {
		Description("Attributes for Devices or Neighbors")
		Attribute("Device Attribute", device, func() {
		})
		Attribute("Neighbor Attribute", neighbor, func() {
		})
	})
})

`var device = Type("Device", func() {
	Description("Device attributes")
	Attribute("normal_status", String, "device", func() {
		devStatus()
	})
})

`var neighbor = Type("Neighbor", func() {
	Description("Attributes for Neighbor")
	Attribute("node", String, "node of the neighbor", func() {
		Example("local")
	})
})
```

Viewing the generated openapi3.yaml file in the Swagger Editor reveals the absence of the neighbor and device schemas. 
The Node type contains the union enum types, but the value section only shows a JSON formatted union value, instead of listing the attributes inside of the Device/Neighbor types. 
![Screenshot from 2022-11-28 14-32-30](https://user-images.githubusercontent.com/119361116/204387258-e5b0477f-7685-4813-a206-43bb768b81b6.png)
The generated yaml does not use the OpenAPI oneOf keyword.

**Comment by seapike** [comment]
I am struggling with the same issue. According to the blog entry and documentation, this should generate the type schemas and reference them like
```    
  Type:
      type: string
      description: |-
        Union type name, one of:
        - "Dog"
        - "Cat"        
      example: Cat
      enum:
      - Dog
      - Cat
Value:
      description: Union value, type must be one of service package types
        listed above
      example: Dog
      anyOf:
      - $ref: '#/components/schemas/Dog'
      - $ref: '#/components/schemas/Cat'
```
But instead it returns a generic:
```
Type:
    type: string
    description: |-
        Union type name, one of:
        - "Cat"
        - "Dog"
    example: Dog
    enum:
        - Cat
        - Dog
Value:
    type: string
    description: JSON formatted union value
    example: '"JSON"'
```

This is using v3.11.3
