### ISSUE TITLE
Need a way to disable unwanted examples produced for swagger

### ISSUE THREAD

**Issue by konstantin-dzreev** [goadesign/goa#776]
Lets say I have a resource that is defined as:
```
var Path = ArrayOf(String)

// A resource with a payload that has:
...
    Attribute("paths", ArrayOf(Path), "foo", func() {
        Example([][]string{{"path1"}, {"path2"}})
    })
```
goa v1 translates it to swagger.yaml as:
```
      paths:
        description: foo
        example:
        - - path1
        - - path2
        items:
          example:
          - Quod voluptatem blanditiis autem maxime praesentium quia.
          items:
            example: Quod voluptatem blanditiis autem maxime praesentium quia.
            type: string
          type: array
        type: array
```
adding unwanted Latin quotes.
It would be nice to have a way to disable them, or to provide my own custom examples that would override these "Quod voluptatem blanditiis autem maxime praesentium quia"s.

**Comment by gagliardetto** [comment]
This is what you are looking for: https://goa.design/reference/goa/design/apidsl/#func-noexample-a-name-apidsl-noexample-a

**Comment by konstantin-dzreev** [comment]
I did, but it did the opposite from what I wanted. It removed
```
        example:
        - - path1
        - - path2
```
but kept
```
        items:
          example:
          - Quod voluptatem blanditiis autem maxime praesentium quia.
          items:
            example: Quod voluptatem blanditiis autem maxime praesentium quia.
            type: string
          type: array
        type: array
```

**Comment by gagliardetto** [comment]
I see... Very interesting. Will try to find another solution.

Il gio 15 set 2016, 18:23 Konstantin Dzreev <notifications@github.com> ha
scritto:

**Comment by gagliardetto** [comment]
```go
var P = ArrayOf(String)
var Path = ArrayOf(P)

    Attribute("paths", Path, "foo", func() {
		P.ElemType.SetExample("")
		Path.ElemType.SetExample("")
        Example([][]string{{"path1"}, {"path2"}})
    })
```

This way you can override the latin examples.

**Comment by konstantin-dzreev** [comment]
Thanks for helping me with this. It is a bit better now, but still slightly weird.

I tried this:
```
var	Path  = ArrayOf(String)
var	Paths = ArrayOf(Path)

func init() {
	Path.ElemType.SetExample(``)
	Paths.ElemType.SetExample(``)
}
```
And it just replaced the Latin sentences with "":
```
        items:
          example:
          - ""
          - ""
          items:
            example: ""
            type: string
          type: array
        type: array
``` 

Then I tried:
```
func init() {
	Path.ElemType.SetExample(`["path1"]`)
	Paths.ElemType.SetExample(`[["path2"], ["path3"]]`)
}
```
and it produced almost what I wanted except for not using Paths example at all:
```
        items:
          example:
          - '["path1"]'   # expected - '["path2"]'
          - '["path1"]'   # expected - '["path3"]'
          items:
            example: "[path1]"
            type: string
          type: array
        type: array
```

**Comment by gagliardetto** [comment]
Please see: https://goa.design/reference/goa/design.html#func-attributedefinition-setexample-a-name-design-attributedefinition-setexample-a:83772ba7ad0304b1562d08f190539946

You could try using

Path.ElemType.SetExample([]string{"one","two"})
Paths.ElemType.SetExample([][]string{{"one","two"},{"three","four"}})

I can't test it right now. SetExample accepts an interface, so it could work.

**Comment by konstantin-dzreev** [comment]
Tried: got the original Latin quotes back, like as if I'd do nothing at all.

**Comment by gagliardetto** [comment]
Ok, maybe I sorted this out:

```go
var Path = ArrayOf(String)
var Paths = ArrayOf(Path)

func init() {
	Path.ElemType.SetExample("path7") // Path is considered to be a string; the example must be a string
	Paths.ElemType.SetExample([]string{"path5", "path6"}) // Paths is considered to be an array of strings; the example must be an array of strings
}
// ...
	Attribute("paths", Paths, "foo", func() {
		Example([][]string{{"path1", "path2"}, {"path3", "path4"}}) // paths is considered to be an array of arrays of strings; must have an example of an array of arrays of strings
	})
```

```yaml
      paths:
        description: foo
        example:
        - - path1
          - path2
        - - path3
          - path4
        items:
          example:
          - path5
          - path6
          items:
            example: path7
            type: string
          type: array
        type: array
```

I'm not sure why...

**Comment by gagliardetto** [comment]
P.S.

If you put NoExample() in the Resource or even in the api, no Latin examples will be generated at all. Swagger will list only the examples provided by you.

**Comment by konstantin-dzreev** [comment]
```
func init() {
    // Path is considered to be a string; the example must be a string
    Path.ElemType.SetExample("path7")
    // Paths is considered to be an array of strings; the example must be an array of strings
    Paths.ElemType.SetExample([]string{"path5", "path6"})
}
```
Worked perfectly, thanks!

P.S. And I tried NoExample() again on both API and Resource level: in both the cases it did remove my examples and kept the auto-generated Latin ones.

**Comment by gagliardetto** [comment]
> P.S. And I tried NoExample() again on both API and Resource level: in both the cases it did remove my examples and kept the auto-generated Latin ones.

Here is what I get:

```yaml
      paths:
        description: foo
        example:
        - - path1
          - path2
        - - path3
          - path4
        items:
          items:
            type: string
          type: array
        type: array
```

... using:

```go
var Path = ArrayOf(String)
var Paths = ArrayOf(Path)

// nothing in init()

	Attribute("paths", Paths, "foo", func() {
		Example([][]string{{"path1", "path2"}, {"path3", "path4"}})
	})
```

... and:

```go
var _ = API("someapi", func() {
	Title("Some title")
	Description("Some description")
	Host("localhost:8080")
	Scheme("http")
	NoExample()
})
```
